@startuml
title Sequence Diagram - Add Command
actor user

participant ":UI" as ui
participant ":PayPals" as pp
participant ":Parser" as parser
participant ":AddCommand" as addCmd
participant ":Activity" as activity
participant ":ActivityManager" as mgr
participant ":Storage" as storage

activate pp
pp -> ui : readLine()
activate ui
user -> ui : "add d/... n/... f/... a/..."
ui --> pp : fullCommand
pp -> parser : decodeCommand(...)
activate parser
parser -> addCmd ** : AddCommand(...)
activate addCmd
addCmd --> parser :
deactivate addCmd
parser --> pp : addCommand
deactivate parser

pp -> addCmd : execute(...)
activate addCmd
addCmd -> activity ** : Activity(...)
activate activity
activity --> addCmd :
deactivate activity

addCmd -> mgr : addActivity(...)
activate mgr
mgr --> addCmd :
deactivate mgr

addCmd -> ui : print confirmation
ui --> addCmd :
addCmd --> pp
deactivate addCmd

pp -> storage : save(...)
activate storage
storage --> pp :
deactivate storage
ui --> user :
deactivate ui

@enduml
