@startuml
title Sequence Diagram - List Command
actor user

participant ":Ui" as ui
participant ":PayPals" as pp
participant ":Parser" as parser
participant ":ListCommand" as listCmd
participant ":ActivityManager" as mgr

activate pp
pp -> ui : readLine()
activate ui
user -> ui : "list"
ui --> pp : fullCommand

pp -> parser : decodeCommand(...)
activate parser
parser -> listCmd **: ListCommand(...)
activate listCmd
listCmd --> parser :
deactivate listCmd
deactivate parser

pp -> listCmd : execute(...)
activate listCmd
listCmd -> mgr : getActivityList(...)
activate mgr
mgr --> listCmd :
deactivate mgr

listCmd -> ui : print activities
ui --> listCmd :

listCmd --> pp
deactivate listCmd
ui --> user
deactivate ui
@enduml
