@startuml
skinparam classAttributeIconSize 0
hide circle

class PayPals
class "{abstract}\nCommand"
class UI
class Storage
class Parser
class ActivityManager
class Activity
class Person

PayPals -> "{abstract}\nCommand"
PayPals "1" -d-> "1" Storage
PayPals "1" -l-> "1" UI
PayPals "1" -u-> "1" Parser
PayPals "1"-> "1" ActivityManager
ActivityManager "1" o-- "*" Activity
Activity "1" o-r- "0..*" Person : owes

@enduml