@startuml
!include Style.puml


' Define components and their colors
actor User
rectangle {
  rectangle Ui LOGIC_COLOR_R
  rectangle Parser LOGIC_COLOR_Y
  rectangle Command LOGIC_COLOR_G
  rectangle Activity LOGIC_COLOR_B
  rectangle Storage LOGIC_COLOR_P
  rectangle Paypals
}
file Files #lightyellow

' Define relationships between components
User -[#black,dashed]down-> Ui
Paypals --> Ui
Paypals --> Storage
Storage -[LOGIC_COLOR_P]-> Activity
Storage -[LOGIC_COLOR_P,dashed]-> Files
Paypals --> Command
Command -[LOGIC_COLOR_G]-> Activity
Paypals --> Parser

@enduml

