@startuml
title Sequence Diagram - Split Command
actor user

participant "ui:Ui" as ui
participant ":PayPals" as pp
participant "parser:Parser" as parser
participant "splitCmd:SplitCommand" as splitCmd
participant "mgr:ActivityManager" as mgr
participant "activity:Activity" as activity

activate pp
pp -> ui : readLine()
activate ui
user -> ui : enterCommand("split")
ui --> user
pp -> parser : decodeCommand(...)
activate parser
parser -> splitCmd **: SplitCommand(...)
activate splitCmd
splitCmd --> parser :
deactivate splitCmd
parser --> pp
deactivate parser

pp -> splitCmd : execute(...)
activate splitCmd
splitCmd -> mgr : getActivity(...)
activate mgr
mgr --> splitCmd :
deactivate mgr

splitCmd -> activity : getPayer(...)
activate activity
activity --> splitCmd :
deactivate activity

splitCmd -> activity : getAllFriends(...)
activate activity
activity --> splitCmd :
deactivate activity

splitCmd -> ui : print transactions
ui --> splitCmd :
splitCmd --> pp
deactivate splitCmd
ui --> user :
deactivate ui
@enduml
